// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsomwT6UtOwqzZCCVaYKsNnbLH2xQvRAU',
    appId: '1:140473618678:web:47cfc719ea9f476f1f5cd7',
    messagingSenderId: '140473618678',
    projectId: 'auth-app-b0c1f',
    authDomain: 'auth-app-b0c1f.firebaseapp.com',
    storageBucket: 'auth-app-b0c1f.firebasestorage.app',
    measurementId: 'G-YGHC3BXH56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnxAilc-4lFxcPGPVKaV6HPSs0WAu9tas',
    appId: '1:140473618678:android:15373c9dfa1cdf3a1f5cd7',
    messagingSenderId: '140473618678',
    projectId: 'auth-app-b0c1f',
    storageBucket: 'auth-app-b0c1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTw3APbsSqpQlcc-zhJTxZ_0mObj_7ARM',
    appId: '1:140473618678:ios:f27cbcc063e830871f5cd7',
    messagingSenderId: '140473618678',
    projectId: 'auth-app-b0c1f',
    storageBucket: 'auth-app-b0c1f.firebasestorage.app',
    androidClientId: '140473618678-bqi357oeqi7g0eb10l4l2qo6adn85obs.apps.googleusercontent.com',
    iosClientId: '140473618678-p8kno8sp7tcf66h5ap624p6720tb9vhe.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTw3APbsSqpQlcc-zhJTxZ_0mObj_7ARM',
    appId: '1:140473618678:ios:f27cbcc063e830871f5cd7',
    messagingSenderId: '140473618678',
    projectId: 'auth-app-b0c1f',
    storageBucket: 'auth-app-b0c1f.firebasestorage.app',
    androidClientId: '140473618678-bqi357oeqi7g0eb10l4l2qo6adn85obs.apps.googleusercontent.com',
    iosClientId: '140473618678-p8kno8sp7tcf66h5ap624p6720tb9vhe.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsomwT6UtOwqzZCCVaYKsNnbLH2xQvRAU',
    appId: '1:140473618678:web:01b459ec7733f01d1f5cd7',
    messagingSenderId: '140473618678',
    projectId: 'auth-app-b0c1f',
    authDomain: 'auth-app-b0c1f.firebaseapp.com',
    storageBucket: 'auth-app-b0c1f.firebasestorage.app',
    measurementId: 'G-J4GD669VX3',
  );
}
